### ISSUE TITLE
DBT DREMIO CANNOT RUN WITH UNION ALL 

### ISSUE THREAD

**Issue by thuybt** [fabrice-etanchaud/dbt-dremio#24] opened 2022-04-02 04:29 UTC
Hi Fabrice, 
Lately, I have using dremio-dbt to run create or replace a view 
```
CREATE OR REPLACE VIEW AS "credit_overview_1923" AS 
(
    WITH temp_table AS (
    SELECT 1 as name
    UNION ALL
    SELECT 2 as name
    )
    SELECT *
    FROM temp_table
)


```
then Dremio make in parsing query error but
when I run 
```
WITH temp_table AS (
    SELECT 1 as name
    UNION ALL
    SELECT 2 as name
    )
    SELECT *
    FROM temp_table
```
it complete successfully 

Please indicate the root cause of this problems, and the solution. Thank you so much

**Comment by fabrice-etanchaud** [comment] 2022-04-04 19:57
Hi @thuybt , thank you for using dbt-dremio !
The problem is not in the adapter,
as the problem still remains when you try executin the query in the dremio UI (I am pretty sure there is no AS between VIEW and the view name)

CREATE OR REPLACE VIEW <<AS>> "credit_overview_1923" AS 
(
    WITH temp_table AS (
    SELECT 1 as name
    UNION ALL
    SELECT 2 as name
    )
    SELECT *
    FROM temp_table
)

But this works : 

CREATE OR REPLACE VIEW "credit_overview_1923" AS 
(
    WITH temp_table(name) AS (
   VALUES(1),(2)
    )
    SELECT *
    FROM temp_table
)

It must be a calcite parsing problem, I will try to find out more on the web.

**Comment by fabrice-etanchaud** [comment] 2022-04-28 17:54
Hi @thuybt , as this not dbt-dremio's fault, I will close this issue if you don't mind.
Would you please give the new adapter version a try ?
Best,

**Closed by fabrice-etanchaud** 2022-04-28 17:54 UTC
